# Numpy Tutorial

In [81]:
%config Completer.use_jedi = True

### Import Numpy

In [1]:
import numpy as np

In [2]:
x = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])

In [30]:
print("Unique ID    :",id(x))
print("Size         :",x.size)
print("Dimensions   :",x.ndim)
print("Shape        :",x.shape)
print("Dtype        :",x.dtype)
print("Flags        :",x.flags)
print("Strides      :",x.strides)

Unique ID    : 140259952615472
Size         : 30
Dimensions   : 2
Shape        : (3, 10)
Dtype        : int64
Flags        :   C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

Strides      : (80, 8)


## Slicing

In [9]:
x = np.array([range(0,10),range(10,20),range(20,30)])

In [11]:
x[:,:]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

Get the 3rd and 4th elemenet from the second and third row

In [15]:
x[1:,3:5]

array([[13, 14],
       [23, 24]])

Get the last element from all the rows

In [21]:
x[:,-1]

array([ 9, 19, 29])

In [22]:
x[:,x.shape[1]-1]

array([ 9, 19, 29])

How to get the alternative numbers or skip N step elements 

In [28]:
# Just taking 1 row of data for example purpose. I want to skip 2 elements after every selected element
x[0][::3]

array([0, 3, 6, 9])

# Copy Variables

We have two types of copies
1. copy()
2. deepcopy()

Every object has a unique identifier and if any two variables having the same id value, then they are referring to the same piece of data in the memory. If one variable value changes, it reflects in the other one.

In [58]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = np.array([a, b])

Every variable has assigned to a differnt id value as follows

In [59]:
id(a),id(b),id(c)

(140260217973040, 140260217972560, 140260217973808)

Now,

In [60]:
d = c

Using normal assignment operatings to copy:

In [61]:
print(id(c) == id(d))          # True - d is the same object as c
print(id(c[0]) == id(d[0]))    # True - d[0] is the same object as c[0]

True
True


Using a shallow copy:

In [62]:
d = c.copy()                   # can also use __copy__()

print(id(c) == id(d))          # False - d is now a new object
print(id(c[0]) == id(d[0]))    # True - d[0] is the same object as c[0]

False
True


Using a deep copy:

In [66]:
import copy                   # Use copy package

d = copy.deepcopy(c)

print(id(c) == id(d))          # False - d is now a new object
print(id(c[0]) == id(d[0]))    # False - d[0] is now a new object

False
True


##### Note: Above example is correct but somehow, deepcopy is not working as expected. 

## Mathematical Operations

In [72]:
x = np.array([range(0,10),range(10,20),range(20,30),range(30,40)])
x

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [73]:
x.shape,x.size

((4, 10), 40)

In [77]:
np.sum(x)               # Sum all the elements

780

In [78]:
np.sum(x,axis=0)        # Sum elements column wise

array([60, 64, 68, 72, 76, 80, 84, 88, 92, 96])

In [79]:
np.sum(x,axis=1)        # Sum elements row wise

array([ 45, 145, 245, 345])

## Reshape

In [84]:
x  = np.random.randint(0,100,100)

In [86]:
x.shape

(100,)

In [91]:
x.reshape(5,20)

array([[39, 97, 30, 13, 81, 94,  4, 13, 22,  2, 54, 72, 89, 40, 92, 26,
        43,  0, 27, 91],
       [63, 90, 20, 34, 58, 60, 80,  9,  5, 25, 83, 94, 34,  4, 90, 92,
        14, 66, 11, 67],
       [ 1, 42,  7, 38, 59,  7, 20, 77, 28, 33, 94, 45, 35,  1, 86, 33,
        44, 82, 13, 29],
       [78, 86, 25, 73, 48, 89, 86, 54,  5, 68, 44, 67, 44, 62, 29,  8,
        15, 83, 26, 44],
       [11, 60, 12, 23,  7, 61, 82, 39, 39, 20, 14, 95, 10, 80, 32, 49,
         8, 38, 91, 73]])

## Filters

In [100]:
x  = np.random.randint(0,100,50)

In [101]:
x

array([75, 69, 70, 76,  2, 55, 25, 64, 95, 55, 85, 64, 28,  1, 82, 76,  6,
       59, 62, 36, 51, 77,  4, 86, 50, 92, 65, 23, 39, 17, 42, 72, 62, 42,
       82, 37, 55, 45, 79, 86, 50, 75, 74, 56, 40, 27, 79,  9, 59,  0])

In [102]:
x[x>50]                 # Returns the values that satisfies the filter condition

array([75, 69, 70, 76, 55, 64, 95, 55, 85, 64, 82, 76, 59, 62, 51, 77, 86,
       92, 65, 72, 62, 82, 55, 79, 86, 75, 74, 56, 79, 59])

In [108]:
x = copy.copy(x.reshape(5,10))

In [112]:
x[x>50]                 # Still return the values as a single array without preserving the original shape

array([75, 69, 70, 76, 55, 64, 95, 55, 85, 64, 82, 76, 59, 62, 51, 77, 86,
       92, 65, 72, 62, 82, 55, 79, 86, 75, 74, 56, 79, 59])

In [120]:
print(np.argmin(x))             # Returns the indices of the minimum value along the axis
print(np.argmin(x,axis=0))      # Returns the indices of the minimum value along the column
print(np.argmin(x,axis=1))      # Returns the indices of the minimum value along the row

49
[3 1 2 1 0 4 1 4 2 4]
[4 3 2 5 9]


In [123]:
x

array([[75, 69, 70, 76,  2, 55, 25, 64, 95, 55],
       [85, 64, 28,  1, 82, 76,  6, 59, 62, 36],
       [51, 77,  4, 86, 50, 92, 65, 23, 39, 17],
       [42, 72, 62, 42, 82, 37, 55, 45, 79, 86],
       [50, 75, 74, 56, 40, 27, 79,  9, 59,  0]])

In [124]:
np.var(x,axis=0)               # Returns the variance of each column

array([270.64,  21.04, 738.24, 889.76, 888.96, 577.84, 714.4 , 442.4 ,
       360.16, 895.76])

In [137]:
v = np.var(x,axis=0)
np.argsort(v)                   # Returns the indices of the variances in the sorted order in default ascending order
high_var = np.argsort(v)[-3:]   # Take the top three high variance indices
high_var

array([4, 3, 9])

In [139]:
x[:,high_var]                   # Return the columns with high variancve

array([[ 2, 76, 55],
       [82,  1, 36],
       [50, 86, 17],
       [82, 42, 86],
       [40, 56,  0]])

### Use where to Filter

In [233]:
x  = np.random.randint(0,100,50)
x

array([71, 88, 32, 17, 10, 23, 15, 86, 74, 96, 53, 79, 83, 85,  6,  1, 53,
       38, 53, 59, 28, 23, 63, 15, 16, 91, 12, 82, 15, 24,  0, 69, 82, 72,
       50, 19, 40, 74, 17, 23, 78, 78, 11, 15, 96, 15, 11, 28, 97, 18])

In [235]:
np.where(x<50)        # Returns the values that satisfies the filter condition

(array([ 2,  3,  4,  5,  6, 14, 15, 17, 20, 21, 23, 24, 26, 28, 29, 30, 35,
        36, 38, 39, 42, 43, 45, 46, 47, 49]),)

## Broadcasting

In [161]:
x = np.array(range(0,20))
y = 20

In [157]:
x + y                           # Element wise addition

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
       37, 38, 39])

In [164]:
y = np.array([1,2,3,4])         # Use a array instead of a scaler

In [165]:
x + y

ValueError: operands could not be broadcast together with shapes (20,) (4,) 

In [166]:
x = x.reshape(4,5)
x.shape, y.shape

((4, 5), (4,))

In [168]:
x + y

ValueError: operands could not be broadcast together with shapes (4,5) (4,) 

In [171]:
y = y.reshape(4,1)
y.shape

(4, 1)

In [172]:
x + y

array([[ 1,  2,  3,  4,  5],
       [ 7,  8,  9, 10, 11],
       [13, 14, 15, 16, 17],
       [19, 20, 21, 22, 23]])

In [173]:
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [174]:
y

array([[1],
       [2],
       [3],
       [4]])

## Matrix Operation

In [177]:
aMatrx = np.array([[1,1,1],[2,2,2]])
bMatrx = np.array([[3,3,3],[4,4,4]])

In [180]:
aMatrx,bMatrx

(array([[1, 1, 1],
        [2, 2, 2]]),
 array([[3, 3, 3],
        [4, 4, 4]]))

In [183]:
aMatrx * bMatrx     # Element wise Multiplication

array([[3, 3, 3],
       [8, 8, 8]])

In [184]:
aMatrx.dot(bMatrx)   # Dot Product

ValueError: shapes (2,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)

In [185]:
aMatrx.dot(bMatrx.T)   # Dot Product

array([[ 9, 12],
       [18, 24]])

In [187]:
np.dot(aMatrx,bMatrx.T)

array([[ 9, 12],
       [18, 24]])

In [189]:
aMatrx @ bMatrx.T

array([[ 9, 12],
       [18, 24]])

## More Functions

In [193]:
np.zeros((3,4))                 # returns zeros with the specified shape

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [194]:
np.ones((3,4))                  # returns ones with the specified shape

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [202]:
np.random.random((3,4))         # returns random with the specified shape

array([[0.67969731, 0.35476978, 0.32207844, 0.8439246 ],
       [0.12254128, 0.503756  , 0.45357304, 0.07053365],
       [0.75189662, 0.33125686, 0.62899682, 0.30366683]])

In [204]:
np.linspace(0,10,10)           # returns the N values with equally spaced interval 

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [207]:
r = np.random.random((3,4)) 
np.exp(r)                     #e^x

array([[2.2809157 , 2.4766189 , 1.52812612, 1.36973708],
       [1.47917707, 2.63051816, 1.92798426, 1.47027835],
       [1.10157006, 1.29559599, 1.58877012, 1.71095248]])

In [208]:
np.sqrt(r)

array([[0.90806221, 0.95230997, 0.65118525, 0.56090891],
       [0.62568834, 0.98345353, 0.81023147, 0.62084759],
       [0.3110249 , 0.50889175, 0.68041179, 0.73283711]])

## Flatten 

In [228]:
x = np.array(range(0,20))
x = x.reshape(4,5,1)
x

array([[[ 0],
        [ 1],
        [ 2],
        [ 3],
        [ 4]],

       [[ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9]],

       [[10],
        [11],
        [12],
        [13],
        [14]],

       [[15],
        [16],
        [17],
        [18],
        [19]]])

In [229]:
x.ravel()             # Returns all the elements as a 1-dim array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [232]:
x.squeeze()           # Remove axes of length one from the array

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

## Neural Network Dense Layer Calculation in Numpy

y = x*W+b

x = Input
W = weights
b = bias

In [244]:
x = np.random.random(5)
W = np.random.random((10,5))
b = np.random.random(10)

In [247]:
x,W,b

(array([0.40309742, 0.03047681, 0.31759195, 0.98617297, 0.52096539]),
 array([[0.80438879, 0.38717099, 0.85355585, 0.57639143, 0.73894598],
        [0.07841232, 0.39678878, 0.87215028, 0.11958088, 0.58505128],
        [0.53279894, 0.72035628, 0.69184644, 0.35129985, 0.97634392],
        [0.13734412, 0.72136849, 0.30437657, 0.27836555, 0.01016031],
        [0.90548354, 0.98137672, 0.23234893, 0.65121481, 0.1407994 ],
        [0.58489995, 0.18342309, 0.65962874, 0.97064905, 0.70471222],
        [0.90466662, 0.08828749, 0.29962745, 0.70012221, 0.64061876],
        [0.40783995, 0.81971321, 0.72286901, 0.90756528, 0.92637078],
        [0.71613833, 0.95723385, 0.63076095, 0.23344215, 0.06811412],
        [0.33984405, 0.51313708, 0.19282056, 0.68267904, 0.93880995]]),
 array([0.58985975, 0.27639838, 0.58677185, 0.78033016, 0.43506664,
        0.18997559, 0.27933691, 0.05375438, 0.81977092, 0.56052119]))

In [248]:
np.dot(x,W.T) + b

array([2.15037592, 1.01980584, 1.89830456, 1.23415553, 1.61932814,
       1.9651887 , 1.76603747, 1.85033668, 1.6036419 , 1.93671559])

In [249]:
y = np.dot(x,W.T) + b
np.maximum(1.5,y)

array([2.15037592, 1.5       , 1.89830456, 1.5       , 1.61932814,
       1.9651887 , 1.76603747, 1.85033668, 1.6036419 , 1.93671559])